### ISSUE TITLE
add campaign monitor

### ISSUE THREAD

**Issue by nquinlan** [nquinlan/Email-Intelligence#10]
http://www.campaignmonitor.com/

**Comment by iandouglas** [comment]
Hey Nick,

For companies that send through Campaign Monitor, there's a header of:

X-Complaints-To: abuse@cmail20.com

the '20' value in there may change, but that might help to identify Campaign Monitor as a sender.

**Comment by iandouglas** [comment]
added a PR for this

**Comment by nquinlan** [comment]
Love you Ian! Thanks!
